language: python
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
before_script: flake8 bugsy
script: python setup.py develop && py.test --cov bugsy tests
after_success: coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  # password: see secret PYPI_PASSWORD variable
  on:
    branch: master
    tags: true
    os: linux
    python: 3.7